import type { Sport, State, Venue, User } from "@/db/types";

export const mockSports: Sport[] = [
  { id: "soccer", name: "Soccer", color: "#10b981" }, // Green
  { id: "basketball", name: "Basketball", color: "#f97316" }, // Orange
  { id: "tennis", name: "Tennis", color: "#eab308" }, // Yellow
  { id: "baseball", name: "Baseball", color: "#ef4444" }, // Red
  { id: "football", name: "Football", color: "#92400e" }, // Brown
  { id: "volleyball", name: "Volleyball", color: "#3b82f6" }, // Blue
  { id: "hockey", name: "Hockey", color: "#06b6d4" }, // Cyan
  { id: "golf", name: "Golf", color: "#059669" }, // Dark green
  { id: "water-polo", name: "Water Polo", color: "#14b8a6" }, // Teal
];

export const mockStates: State[] = [
  { abbreviation: "AZ", name: "Arizona" },
  { abbreviation: "CA", name: "California" },
  { abbreviation: "TX", name: "Texas" },
  { abbreviation: "NY", name: "New York" },
  { abbreviation: "FL", name: "Florida" },
];

export const mockVenues: Venue[] = [
  {
    id: "venue-1",
    name: "Phoenix Sports Arena",
    city: "Phoenix",
    stateAbbr: "AZ",
    zipCode: "85001",
    address1: "123 Main St",
    phone: "(602) 555-0100",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "venue-2",
    name: "LA Sports Complex",
    city: "Los Angeles",
    stateAbbr: "CA",
    zipCode: "90001",
    address1: "456 Olympic Blvd",
    phone: "(213) 555-0200",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "venue-3",
    name: "Austin Tennis Center",
    city: "Austin",
    stateAbbr: "TX",
    zipCode: "78701",
    address1: "789 Tennis Dr",
    phone: "(512) 555-0300",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "venue-4",
    name: "Miami Beach Volleyball Courts",
    city: "Miami",
    stateAbbr: "FL",
    zipCode: "33139",
    address1: "1000 Ocean Dr",
    phone: "(305) 555-0400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockUser: User = {
  id: "user-1",
  displayName: "John Doe",
  avatarUrl: null,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const mockEvents = [
  {
    id: "event-6",
    name: "Morning Basketball Practice",
    sportId: "basketball",
    startsAt: new Date("2025-10-14T09:00:00"), // Today
    description: "Team practice session for upcoming tournament",
    venueId: "venue-1",
    ownerId: "user-1",
    createdAt: new Date(),
    updatedAt: new Date(),
    sport: { id: "basketball", name: "Basketball", color: "#f97316" },
    venue: {
      id: "venue-1",
      name: "Phoenix Sports Arena",
      city: "Phoenix",
      stateAbbr: "AZ",
      zipCode: "85001",
      address1: "123 Main St",
      phone: "(602) 555-0100",
      createdAt: new Date(),
      updatedAt: new Date(),
      state: { abbreviation: "AZ", name: "Arizona" },
    },
    owner: mockUser,
  },
  {
    id: "event-7",
    name: "Wednesday Soccer Match",
    sportId: "soccer",
    startsAt: new Date("2025-10-16T18:00:00"), // Wednesday this week
    description: "Friendly match between local teams",
    venueId: "venue-2",
    ownerId: "user-1",
    createdAt: new Date(),
    updatedAt: new Date(),
    sport: { id: "soccer", name: "Soccer", color: "#10b981" },
    venue: {
      id: "venue-2",
      name: "LA Sports Complex",
      city: "Los Angeles",
      stateAbbr: "CA",
      zipCode: "90001",
      address1: "456 Olympic Blvd",
      phone: "(213) 555-0200",
      createdAt: new Date(),
      updatedAt: new Date(),
      state: { abbreviation: "CA", name: "California" },
    },
    owner: mockUser,
  },
  {
    id: "event-8",
    name: "Saturday Tennis Clinic",
    sportId: "tennis",
    startsAt: new Date("2025-10-18T10:00:00"), // Saturday this week
    description: "Beginner-friendly tennis clinic with professional coaches",
    venueId: "venue-3",
    ownerId: "user-1",
    createdAt: new Date(),
    updatedAt: new Date(),
    sport: { id: "tennis", name: "Tennis", color: "#eab308" },
    venue: {
      id: "venue-3",
      name: "Austin Tennis Center",
      city: "Austin",
      stateAbbr: "TX",
      zipCode: "78701",
      address1: "789 Tennis Dr",
      phone: "(512) 555-0300",
      createdAt: new Date(),
      updatedAt: new Date(),
      state: { abbreviation: "TX", name: "Texas" },
    },
    owner: mockUser,
  },
  {
    id: "event-1",
    name: "Summer Basketball Tournament",
    sportId: "basketball",
    startsAt: new Date("2025-06-15T14:00:00"),
    description: "Annual summer basketball tournament for all skill levels",
    venueId: "venue-1",
    ownerId: "user-1",
    createdAt: new Date(),
    updatedAt: new Date(),
    sport: { id: "basketball", name: "Basketball", color: "#f97316" },
    venue: {
      id: "venue-1",
      name: "Phoenix Sports Arena",
      city: "Phoenix",
      stateAbbr: "AZ",
      zipCode: "85001",
      address1: "123 Main St",
      phone: "(602) 555-0100",
      createdAt: new Date(),
      updatedAt: new Date(),
      state: { abbreviation: "AZ", name: "Arizona" },
    },
    owner: mockUser,
  },
  {
    id: "event-2",
    name: "Youth Soccer League",
    sportId: "soccer",
    startsAt: new Date("2025-07-01T10:00:00"),
    description: "Weekly soccer matches for youth teams",
    venueId: "venue-2",
    ownerId: "user-1",
    createdAt: new Date(),
    updatedAt: new Date(),
    sport: { id: "soccer", name: "Soccer", color: "#10b981" },
    venue: {
      id: "venue-2",
      name: "LA Sports Complex",
      city: "Los Angeles",
      stateAbbr: "CA",
      zipCode: "90001",
      address1: "456 Olympic Blvd",
      phone: "(213) 555-0200",
      createdAt: new Date(),
      updatedAt: new Date(),
      state: { abbreviation: "CA", name: "California" },
    },
    owner: mockUser,
  },
  {
    id: "event-3",
    name: "Spring Tennis Championship",
    sportId: "tennis",
    startsAt: new Date("2025-04-20T09:00:00"),
    description: "Regional tennis championship with prizes for top performers",
    venueId: "venue-3",
    ownerId: "user-1",
    createdAt: new Date(),
    updatedAt: new Date(),
    sport: { id: "tennis", name: "Tennis", color: "#eab308" },
    venue: {
      id: "venue-3",
      name: "Austin Tennis Center",
      city: "Austin",
      stateAbbr: "TX",
      zipCode: "78701",
      address1: "789 Tennis Dr",
      phone: "(512) 555-0300",
      createdAt: new Date(),
      updatedAt: new Date(),
      state: { abbreviation: "TX", name: "Texas" },
    },
    owner: mockUser,
  },
  {
    id: "event-4",
    name: "Beach Volleyball Tournament",
    sportId: "volleyball",
    startsAt: new Date("2025-05-10T08:00:00"),
    description:
      "Two-day beach volleyball tournament with teams from across the state",
    venueId: "venue-4",
    ownerId: "user-1",
    createdAt: new Date(),
    updatedAt: new Date(),
    sport: { id: "volleyball", name: "Volleyball", color: "#3b82f6" },
    venue: {
      id: "venue-4",
      name: "Miami Beach Volleyball Courts",
      city: "Miami",
      stateAbbr: "FL",
      zipCode: "33139",
      address1: "1000 Ocean Dr",
      phone: "(305) 555-0400",
      createdAt: new Date(),
      updatedAt: new Date(),
      state: { abbreviation: "FL", name: "Florida" },
    },
    owner: mockUser,
  },
  {
    id: "event-5",
    name: "Friday Night Football",
    sportId: "football",
    startsAt: new Date("2025-10-25T19:00:00"),
    description: "High school football game under the lights",
    venueId: "venue-1",
    ownerId: "user-1",
    createdAt: new Date(),
    updatedAt: new Date(),
    sport: { id: "football", name: "Football", color: "#92400e" },
    venue: {
      id: "venue-1",
      name: "Phoenix Sports Arena",
      city: "Phoenix",
      stateAbbr: "AZ",
      zipCode: "85001",
      address1: "123 Main St",
      phone: "(602) 555-0100",
      createdAt: new Date(),
      updatedAt: new Date(),
      state: { abbreviation: "AZ", name: "Arizona" },
    },
    owner: mockUser,
  },
];
